services:
    _defaults:
        autowire: true

    contao_company.vcard.generator:
        class: Oveleon\ContaoCompanyBundle\Generator\vCardGenerator

    Oveleon\ContaoCompanyBundle\Controller\vCardController:
        arguments:
            - '@contao_company.vcard.generator'
        tags:
            - controller.service_arguments
